development:
  adapter: postgresql
  encoding: unicode
  database: ga_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ga_production
  pool: 5
  username: postgres
  password:
